# Generated by Django 3.2.20 on 2023-10-25 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0005_auto_20231020_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAvatarORM',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default=None, null=True, upload_to='avatars/')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_avatar', to=settings.LS_ENTERPRISE_MODEL)),
            ],
            options={
                'db_table': 'e_enterprise_avatars',
                'abstract': False,
                'swappable': 'LS_ENTERPRISE_AVATAR_MODEL',
            },
        ),
    ]
