# Generated by Django 3.2.22 on 2023-11-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0010_releaseorm_checksum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorm',
            old_name='is_supper_admin',
            new_name='is_super_admin',
        ),
        migrations.AddField(
            model_name='userorm',
            name='sync_all_platforms',
            field=models.BooleanField(default=False),
        ),
    ]
