# Generated by Django 3.2.22 on 2023-12-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0014_userorm_fd_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='fd_creation_date',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userorm',
            name='fd_last_use_date',
            field=models.FloatField(null=True),
        ),
    ]
