# Generated by Django 3.2.22 on 2023-12-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0015_auto_20231206_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseorm',
            name='platform',
            field=models.CharField(db_index=True, default=None, max_length=32, null=True),
        ),
    ]
