# Generated by Django 3.2.22 on 2023-12-18 06:44

from django.db import migrations, models
import locker_server.api_orm.models.enterprises.enterprises


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0016_releaseorm_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseorm',
            name='avatar',
            field=models.ImageField(default=None, null=True,
                                    upload_to=locker_server.api_orm.models.enterprises.enterprises.image_upload_path),
        ),
    ]
