# Generated by Django 3.2.22 on 2023-12-18 10:15

from django.db import migrations, models
import locker_server.api_orm.models.configurations.app_info


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0017_auto_20231218_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfoORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default=None, null=True,
                                           upload_to=locker_server.api_orm.models.configurations.app_info.image_upload_path)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('creation_date', models.FloatField(default=None, null=True)),
                ('revision_date', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'cs_app_info',
            },
        ),
    ]
