# Generated by Django 3.2.22 on 2023-12-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0018_auto_20231218_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcredentialorm',
            name='type',
            field=models.CharField(default='hmac', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userorm',
            name='fd_type',
            field=models.CharField(default='hmac', max_length=128, null=True),
        ),
    ]
