# Generated by Django 3.2.22 on 2023-12-22 04:53

from django.db import migrations


def update_record(apps, schema_editor):
    MissionORM = apps.get_model('api_orm', 'MissionORM')

    # Update capterra mission
    capterra_mission_orm = MissionORM.objects.get(id="capterra_rating_and_review")
    capterra_mission_orm.available = False
    capterra_mission_orm.save()

    # Update extension mission
    extension_mission_orm = MissionORM.objects.get(id="extension_installation_and_review")
    extension_mission_orm.reward_type = "promo_code"
    extension_mission_orm.reward_value = 5
    extension_mission_orm.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0019_auto_20231221_1159'),
    ]

    operations = [
        migrations.RunPython(update_record),
    ]
