# Generated by Django 3.2.23 on 2024-03-12 08:02
import os
import json

from django.db import migrations, models


FIXTURE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
FIXTURE_FILENAMES = ['plan.json']


def update_records(apps, schema_editor):
    from locker_server.api_orm.models import wrapper
    model_orm = wrapper.get_plan_model()

    for fixture_filename in FIXTURE_FILENAMES:
        fixture_file = os.path.join(FIXTURE_DIR, fixture_filename)
        fixture = open(fixture_file, 'rb')
        data = json.loads(fixture.read())
        for d in data:
            fields = d.get("fields")
            fields["plan_type_id"] = fields.get("plan_type")
            fields.pop("plan_type", None)
            d["fields"] = fields
        for d in data:
            fields = d.get("fields")
            try:
                obj = model_orm.objects.get(alias=fields.get("alias"))
                obj.limit_totp = fields.get("limit_totp")
                obj.save()
            except model_orm.DoesNotExist:
                continue
        print(f"[+] Done updated {len(data)} objects from {fixture_filename}")


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0020_auto_20231222_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmplanorm',
            name='limit_totp',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.RunPython(update_records),
    ]
