# Generated by Django 3.2.23 on 2024-05-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0023_auto_20240403_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcredentialorm',
            name='fd_transports',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userorm',
            name='fd_transports',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
