# Generated by Django 3.2.23 on 2024-05-30 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0024_auto_20240528_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipherHistoryORM',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('creation_date', models.FloatField()),
                ('revision_date', models.FloatField()),
                ('last_use_date', models.FloatField(null=True)),
                ('reprompt', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('data', models.TextField(blank=True, null=True)),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cipher_histories', to=settings.LS_CIPHER_MODEL)),
            ],
            options={
                'db_table': 'cs_cipher_histories',
            },
        ),
    ]
