# Generated by Django 3.2.23 on 2024-06-28 04:39
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models


def load_fixtures(apps, schema_editor):
    from locker_server.api_orm.models import wrapper
    from locker_server.shared.constants.transactions import PLAN_TYPE_PM_FREE
    model_orm = wrapper.get_plan_model()
    try:
        plan = model_orm.objects.get(alias=PLAN_TYPE_PM_FREE)
        plan.limit_history = 3
        plan.save()
        print(f"[+] Saved limit history of free plan")
    except ObjectDoesNotExist:
        pass


def unload_fixtures(apps, schema_editor):
    """ Brutally deleting all entries for this model... """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0025_auto_20240530_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmplanorm',
            name='limit_history',
            field=models.IntegerField(default=None, null=True),
        ),

        # Load data from fixtures
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures),
    ]
