# Generated by Django 3.2.23 on 2024-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0026_auto_20240628_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseorm',
            name='stable',
            field=models.BooleanField(default=False),
        ),
    ]
