# Generated by Django 3.2.23 on 2024-10-30 08:06

from django.db import migrations, models
import locker_server.shared.utils.app


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0029_auto_20240710_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutofillKeyORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512, unique=True)),
                ('values', models.TextField(blank=True, null=True)),
                ('created_time', models.FloatField(default=locker_server.shared.utils.app.now, null=True)),
                ('updated_time', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'extension_autofill_keys',
            },
        )
    ]
