# Generated by Django 3.2.23 on 2024-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0030_auto_20241030_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorm',
            name='click_uuid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        )
    ]
