# Generated by Django 3.2.23 on 2024-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0030_auto_20241030_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofillkeyorm',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
