# Generated by Django 3.2.23 on 2024-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0031_auto_20241209_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorm',
            name='click_uuid_sender',
            field=models.CharField(max_length=16, null=True),
        )
    ]
