# Generated by Django 3.2.23 on 2024-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0032_auto_20241209_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofillkeyorm',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        )
    ]
