# Generated by Django 3.2.23 on 2025-02-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0033_auto_20241211_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmuserplanorm',
            name='saas_license',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
