# Generated by Django 3.2.23 on 2025-02-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0034_auto_20250204_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmplanorm',
            name='limit_total',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
