# Generated by Django 3.2.23 on 2025-04-14 11:02

from django.db import migrations, models
import locker_server.shared.utils.app


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0036_auto_20250318_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayaddressorm',
            name='latest_used_time',
            field=models.FloatField(default=locker_server.shared.utils.app.now),
        ),
    ]
