# Generated by Django 3.2.23 on 2025-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0037_auto_20250414_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipherorm',
            name='deleted_date',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cipherorm',
            name='revision_date',
            field=models.FloatField(db_index=True),
        ),
    ]
