# Generated by Django 3.2.23 on 2025-04-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0038_auto_20250416_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipherorm',
            name='type',
            field=models.IntegerField(db_index=True),
        ),
    ]
