# Generated by Django 3.2.23 on 2025-05-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0039_auto_20250416_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='hide_master_password',
            field=models.BooleanField(default=False),
        ),
    ]
