# Generated by Django 3.2.23 on 2025-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0040_auto_20250520_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseorm',
            name='enterprise_entity_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='enterpriseorm',
            name='enterprise_registration_date',
            field=models.FloatField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='enterpriseorm',
            name='enterprise_registration_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='enterpriseorm',
            name='enterprise_vat_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
