# Generated by Django 3.2.23 on 2025-07-26 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import locker_server.shared.utils.app


class Migration(migrations.Migration):
    dependencies = [
        ('api_orm', '0041_auto_20250609_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamSettingCategoryORM',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('name_vi', models.CharField(max_length=512)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cs_scam_setting_categories',
            },
        ),
        migrations.CreateModel(
            name='ScamSettingORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.FloatField(default=locker_server.shared.utils.app.now, null=True)),
                ('updated_at', models.FloatField(default=None, null=True)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_settings',
                                   to='api_orm.scamsettingcategoryorm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_settings',
                                           to=settings.LS_USER_MODEL)),
            ],
            options={
                'db_table': 'cs_user_scam_settings',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
