# Generated by Django 3.2.23 on 2025-07-29 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import locker_server.shared.utils.app
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0042_auto_20250726_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistScamUrlORM',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=512)),
                ('created_at', models.FloatField(default=locker_server.shared.utils.app.now, null=True)),
                ('updated_at', models.FloatField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_urls', to=settings.LS_USER_MODEL)),
            ],
            options={
                'db_table': 'cs_whitelist_scam_urls',
                'unique_together': {('user', 'url')},
            },
        ),
    ]
