# Generated by Django 5.2.11 on 2026-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0043_auto_20250729_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorm',
            name='base32_secret_factor2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
