# Generated by Django 5.2.12 on 2026-04-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0044_alter_enterprisememberorm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='kdf_memory',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userorm',
            name='kdf_parallelism',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
