# Generated by Django 5.2.12 on 2026-04-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0045_userorm_kdf_memory_userorm_kdf_parallelism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcredentialorm',
            name='kdf_memory',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='backupcredentialorm',
            name='kdf_parallelism',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
