# Generated by Django 5.2.13 on 2026-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0046_backupcredentialorm_kdf_memory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberorm',
            name='accepted_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
