AUTOFILL_CACHE = 'autofill_keys'
DEFAULT_AUTOFILL = {
    "password": [
        "password",
        "o-password",
        "oldpassword",
        "old password",
        "old-password",
        "old_password",
        "login-password"
    ],
    "newPassword": [
        "new password",
        "new-password",
        "new_password",
        "n-password",
        "n_password",
        "newpassword",
        "confirm password",
        "confirm-password",
        "confirm_password",
        "c-password"
    ],
    "username": [
        "username",
        "user name",
        "user_id",
        "user id",
        "user-name",
        "user-id",
        "screen-name",
        "customer id",
        "login id",
        "login",

        "identifiant"
    ],
    "title": [
        "honorific-prefix",
        "prefix",
        "title"
    ],
    "firstName": [
        "firstname",
        "first name",
        "first_name",
        "f-name",
        "first-name",
        "given-name",
        "first-n",
        "cc-given-name"
    ],
    "middleName": [
        "m-name",
        "middle-name",
        "additional-name",
        "middle-initial",
        "middle-n",
        "middle-i"
    ],
    "lastName": [
        "lastname",
        "last name",
        "last_name",
        "last-name",
        "l-name",
        "s-name",
        "surname",
        "family-name",
        "family-n",
        "last-n",
        "cc-family-name"
    ],
    "email": [
        ".com",
        "email",
        "e-mail",
        "email address",
        "email_address",
        "email-address",
        "e-mail address",
        "your email address",
        "corporate email",
        "corporate_email",
        "corporate-email",
        "user_email",
        "user email",
        "user-email"
    ],
    "company": [
        "company",
        "company-name",
        "organization",
        "organization-name"
    ],
    "fullName": [
        "name",
        "fullname",
        "full name",
        "full-name",
        "full_name",
        "your-name",
        "your name",
        "your_name"
    ],
    "phone": [
        "phone",
        "mobile",
        "mobile-phone",
        "tel",
        "telephone",
        "phone-number",
        "phone ext",
        "phone-ext"
    ],
    "ssn": [
        "ssn",
        "social-number",
        "social number",
        "security-number",
        "security number",
        "social security number",
        "social-security-number"
    ],
    "passportNumber": [
        "passport",
        "passport-number",
        "passport number",
        "passport-id",
        "passport id"
    ],
    "licenseNumber": [
        "license",
        "license-number",
        "license number",
        "license-id",
        "license id"
    ],
    "address1": [
        "address",
        "street-address",
        "addr",
        "street",
        "mailing-addr",
        "billing-addr",
        "mail-addr",
        "bill-addr",
        "address-1",
        "address-line-1",
        "addr-1",
        "street-1"
    ],
    "address2": [
        "address-2",
        "address-line-2",
        "addr-2",
        "street-2"
    ],
    "address3": [
        "address-3",
        "address-line-3",
        "addr-3",
        "street-3"
    ],
    "city": [
        "city",
        "r-city",
        "town",
        "region",
        "address-level-2",
        "address-city",
        "address-town"
    ],
    "state": [
        "state",
        "unit",
        "suite",
        "province",
        "provence",
        "address-level-1",
        "address-state",
        "address-province",
        "address-unit",
        "address.unit"
    ],
    "country": [
        "country",
        "country-code",
        "country-name",
        "address-country",
        "address-country-name",
        "address-country-code"
    ],
    "postalCode": [
        "postal",
        "zip",
        "zip2",
        "zip-code",
        "postal-code",
        "post-code",
        "address-zip",
        "address-postal",
        "address-code",
        "address-postal-code",
        "address-zip-code"
    ],
    "cardholderName": [
        "cc-name",
        "cc_name",
        "cc name",
        "card-name",
        "card_name",
        "card name",
        "holder-name",
        "holder name",
        "holder_name",
        "cardholder-name",
        "cardholder_name",
        "cardholder name",
        "cardholder",
        "nom",
        "name of card"
    ],
    "brand": [
        "cc-type",
        "card-type",
        "card-brand",
        "cc-brand",
        "cb-type"
    ],
    "number": [
        "cc number",
        "cc-number",
        "cc-num",
        "cardnumber",
        "card-number",
        "card number",
        "card_number",
        "card-num",
        "cc-no",
        "card-no",
        "creditcard",
        "credit-card",
        "numero-carte",
        "carte",
        "carte-credit",
        "num-carte",
        "cb-num",
        "card-pan",
        "cc_no"
    ],
    "expiration": [
        "cc-exp",
        "card-exp",
        "cc-expiration",
        "card-expiration",
        "cc-ex",
        "card-ex",
        "card-expire",
        "card-expiry",
        "validite",
        "expiration",
        "expiry",
        "mm-yy",
        "mm-yyyy",
        "yy-mm",
        "yyyy-mm",
        "expiration-date",
        "payment-card-expiration",
        "payment-cc-date",
        "expirydate"
    ],
    "expMonth": [
        "exp-month",
        "cc-exp-month",
        "cc-month",
        "card-month",
        "cc-mo",
        "card-mo",
        "exp-mo",
        "card-exp-mo",
        "cc-exp-mo",
        "card-expiration-month",
        "expiration-month",
        "cc-mm",
        "cc-m",
        "card-mm",
        "card-m",
        "card-exp-mm",
        "cc-exp-mm",
        "exp-mm",
        "exp-m",
        "expire-month",
        "expire-mo",
        "expiry-month",
        "expiry-mo",
        "card-expire-month",
        "card-expire-mo",
        "card-expiry-month",
        "card-expiry-mo",
        "mois-validite",
        "mois-expiration",
        "m-validite",
        "m-expiration",
        "expiry-date-field-month",
        "expiration-date-month",
        "expiration-date-mm",
        "exp-mon",
        "validity-mo",
        "exp-date-mo",
        "cb-date-mois",
        "date-m",
        "cc_exp_mm",
        "expirymonth",
        "expiry month"
    ],
    "expYear": [
        "exp-year",
        "cc-exp-year",
        "cc-year",
        "card-year",
        "cc-yr",
        "card-yr",
        "exp-yr",
        "card-exp-yr",
        "cc-exp-yr",
        "card-expiration-year",
        "expiration-year",
        "cc-yy",
        "cc-y",
        "card-yy",
        "card-y",
        "card-exp-yy",
        "cc-exp-yy",
        "exp-yy",
        "exp-y",
        "cc-yyyy",
        "card-yyyy",
        "card-exp-yyyy",
        "cc-exp-yyyy",
        "expire-year",
        "expire-yr",
        "expiry-year",
        "expiry-yr",
        "card-expire-year",
        "card-expire-yr",
        "card-expiry-year",
        "card-expiry-yr",
        "an-validite",
        "an-expiration",
        "annee-validite",
        "annee-expiration",
        "expiry-date-field-year",
        "expiration-date-year",
        "cb-date-ann",
        "expiration-date-yy",
        "expiration-date-yyyy",
        "validity-year",
        "exp-date-year",
        "date-y",
        "cc_exp_yyyy",
        "expiryyear",
        "expiry year"
    ],
    "code": [
        "cvv",
        "cvc",
        "cvv2",
        "cc-csc",
        "cc-cvv",
        "card-csc",
        "card-cvv",
        "cvd",
        "cid",
        "cvc2",
        "cnv",
        "cvn2",
        "cc-code",
        "card-code",
        "code-securite",
        "security-code",
        "crypto",
        "card-verif",
        "verification-code",
        "csc",
        "ccv",
        "cvn",
        "card_cvn",
        "security code",
        "cardsecuritycode"
    ],
    "otp": [
        "otp",
        "pin",
        "totp",
        "code",
        "otp code",
        "otpcode",
        "otp-code",
        "otp_code",
        "app_otp",
        "app_totp",
        "code 2fa",
        "code_2fa",
        "one-time-code",
        "authentication",
        "authentification",
        "authenticator__code",
        "authentication code",
        "twofactor_token",
        "entrez les 6 chiffres",
        "otp-input-1",
        "otp-input-2",
        "otp-input-3",
        "otp-input-4",
        "otp-input-5",
        "otp-input-6",
        "totp_value",
        "totp value",
        "auth-mfa-otpcode"
    ],
    "button": [
        "login",
        "log in",
        "register",
        "sign in",
        "sign-in",
        "sign up",
        "signup",
        "continue",
        "next",
        "create",
        "update",
        "save",
        "save new password",
        "login-submit",
        "create your deel account",
        "create your account",
        "loading..."
    ]
}
