from django.conf import settings

E_MEMBER_ROLE_PRIMARY_ADMIN = "primary_admin"
E_MEMBER_ROLE_ADMIN = "admin"
E_MEMBER_ROLE_MEMBER = "member"

ENTERPRISE_LIST_ROLE = [E_MEMBER_ROLE_PRIMARY_ADMIN, E_MEMBER_ROLE_ADMIN, E_MEMBER_ROLE_MEMBER]
if settings.SELF_HOSTED:
    E_MEMBER_STATUS_INVITED = "created"
    E_MEMBER_STATUS_CONFIRMED = "accessed"
else:
    E_MEMBER_STATUS_INVITED = "invited"
    E_MEMBER_STATUS_CONFIRMED = "confirmed"

E_MEMBER_STATUS_REQUESTED = "requested"
