RELEASE_ENVIRONMENT_PROD = "prod"
RELEASE_ENVIRONMENT_STAGING = "staging"
LIST_RELEASE_ENVIRONMENT = [RELEASE_ENVIRONMENT_PROD, RELEASE_ENVIRONMENT_STAGING]


RELEASE_PLATFORM_LINUX = "linux"
RELEASE_PLATFORM_WINDOWS = "windows"
RELEASE_PLATFORM_MAC_ARM64 = "mac-arm64"
RELEASE_PLATFORM_MAC_X64 = "mac-x64"
LIST_RELEASE_PLATFORM = [RELEASE_PLATFORM_LINUX, RELEASE_PLATFORM_WINDOWS,
                         RELEASE_PLATFORM_MAC_ARM64, RELEASE_PLATFORM_MAC_X64]
