RELEASE_ENVIRONMENT_PROD = "prod"
RELEASE_ENVIRONMENT_STAGING = "staging"
LIST_RELEASE_ENVIRONMENT = [RELEASE_ENVIRONMENT_PROD, RELEASE_ENVIRONMENT_STAGING]

RELEASE_PLATFORM_LINUX = "linux"
RELEASE_PLATFORM_LINUX_ARM = "linux-arm64"
RELEASE_PLATFORM_WINDOWS = "windows"
RELEASE_PLATFORM_MAC_ARM64 = "mac-arm64"
RELEASE_PLATFORM_MAC_X64 = "mac-x64"

RELEASE_PLATFORM_EDGE = "edge"
RELEASE_PLATFORM_SAFARI = "safari"
RELEASE_PLATFORM_FIREFOX = "firefox"
RELEASE_PLATFORM_CHROME = "chrome"

LIST_RELEASE_PLATFORM = [
    RELEASE_PLATFORM_LINUX, RELEASE_PLATFORM_WINDOWS, RELEASE_PLATFORM_MAC_ARM64, RELEASE_PLATFORM_MAC_X64,
    RELEASE_PLATFORM_EDGE, RELEASE_PLATFORM_SAFARI, RELEASE_PLATFORM_FIREFOX, RELEASE_PLATFORM_CHROME,
    RELEASE_PLATFORM_LINUX_ARM
]

ORG_CYSTACK = "cystack"
