SCAM_SETTING_CATEGORY_SHOW_INFO = 'show_safety_info'
SCAM_SETTING_CATEGORY_WARN_ON_SEARCH = 'warn_on_search_results'
SCAM_SETTING_CATEGORY_WARN_ON_LINK = 'warn_on_direct_links'
LIST_SCAM_SETTING_CATEGORIES = [
    SCAM_SETTING_CATEGORY_SHOW_INFO,
    SCAM_SETTING_CATEGORY_WARN_ON_SEARCH,
    SCAM_SETTING_CATEGORY_WARN_ON_LINK,

]
