SSO_PROVIDER_SAML = "saml"
SSO_PROVIDER_OIDC = "oidc"

OIDC_BEHAVIOR_GET = "redirect get"
OIDC_BEHAVIOR_POST = "form post"

LIST_VALID_SSO_PROVIDERS = [
    SSO_PROVIDER_OIDC
]
LIST_OIDC_BEHAVIOR = [OIDC_BEHAVIOR_GET, OIDC_BEHAVIOR_POST]
