# Generated by Django 3.2.20 on 2023-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='base32_secret_factor2',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userorm',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userorm',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userorm',
            name='is_factor2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userorm',
            name='language',
            field=models.CharField(default='en', max_length=4),
        ),
    ]
